---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible==2.2.0.0

  # Check ansible version
  - ansible --version

  # prepare local role dir structure
  - git clone -b ${TRAVIS_BRANCH} --depth 1 git://github.com/${TRAVIS_REPO_SLUG} jackdengtw.crossbow__jenkins_plugins
  - mv jackdengtw.crossbow__jenkins_plugins ..

  # Create ansible.cfg with correct roles_path
  # - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - env ANSIBLE_ROLES_PATH=.. ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
