- name: "INIT | CHECK PARAMETERS"
  # =========================================================================
  assert:
    that:
      - jenkins_home is defined and jenkins_home is not none
      - jenkins_plugins is defined

